### ISSUE TITLE
Screen burn in

### ISSUE THREAD

**Issue by tarmacalastair** [ChandlerSwift/odroidhc4-display#4]
Hello,
In your readme you mention the serious burn-in for this board. Mine is suffering badly from this.
Just wondered if you have found a decent source to replace this? I'm in the UK and the Odroid supplier here doesn't stock them. By the time I source one from overseas it will come to a third of the cost of the entire Odroid HC4.

Thanks for reading.

**Comment by ChandlerSwift** [comment]
I haven't replaced the display on mine. I don't get a ton of use out of that screen (the device sits in an inaccessible corner of my basement, so I basically never look at it directly), so I haven't bothered. If you're okay with doing a bit of soldering work, the docs say that the board is an ssd1306:

https://wiki.odroid.com/odroid-hc4/application_note/oled

So a replacement like this (i2c ssd1306 board for ~$2USD if the link breaks in the future) would probably be reasonable? (First aliexpress result for ssd1306; not an endorsement)

https://www.aliexpress.us/item/3256805784586367.html

**Comment by tarmacalastair** [comment]
Many thanks
